### ISSUE TITLE
无线网络模块是使用的哪个芯片啊

### ISSUE THREAD

**Issue by w450434204** [zhchbin/WeChatAirKiss#3]
使用你这个Demo的话。硬件方面是不是就不需要使用微信提供的哪些芯片了。

**Comment by zhchbin** [comment]
微信提供的芯片是指？我当时测试用的芯片是ESP8266，他们的SDK里支持微信的AirKiss的协议，所以就直接用。也即是说：只要硬件支持AirKiss的协议就行，这个DEMO是拿来替换微信客户端的。

但AirKiss的原理如果弄懂了，自己开发一套协议都可以的。不一定是需要依赖某些硬件或者客户端。
