### ISSUE TITLE
无法解析数据。

### ISSUE THREAD

**Issue by w450434204** [zhchbin/WeChatAirKiss#4]
你好，你这数据是加密的吗？怎么无法解析啊。Airkiss1.0版本吗？

**Comment by zhchbin** [comment]
主要的代码在这里啊：[AirKissEncoder.java](https://github.com/zhchbin/WeChatAirKiss/blob/master/app/src/main/java/me/zhchbin/airkiss/AirKissEncoder.java) 代码都在面前了，仔细看一下就懂的。

看构造函数，传入ssid和密码，得到编码后的数据，没有做AES加密，然后使用UDP发送相应长度的数据包。协议在README.md里有一个[链接](http://wenku.baidu.com/view/a5d51c18561252d380eb6eab.html)
