### ISSUE TITLE
sendPacketAndSleep 里面的怎么理解，求教下

### ISSUE THREAD

**Issue by wsTeamAlliance** [zhchbin/WeChatAirKiss#5]
sendPacketAndSleep 传入的是length,然后那个数组没见到赋值，那么发送出去的是什么，这块可以讲解下么，多谢

**Comment by zhchbin** [comment]
@wsTeamAlliance 你需要看懂AirKiss这个技术的原理。UDP广播包里的内容是什么无所谓的。关键是包的长度信息。
