### ISSUE TITLE
中文WIFI配置不成功，大佬有什么解决方法吗

### ISSUE THREAD

**Issue by chengxinping** [zhchbin/WeChatAirKiss#7]

**Comment by zhchbin** [comment]
这个项目已经是我几年前实现的。当时没有考虑中文WIFI的支持。不过我觉得看一下编码，解决一下Android端发送过去给`ESP8266`的编码转换，问题不大。

不过中文WIFI名估计会长一些。

**Comment by chengxinping** [comment]
我尝试了一下把ssid转成UTF-8格式再传到那个编码组包的类，但是并没有什么用，感觉长度也有点问题

**Comment by zhchbin** [comment]
需要调试一下ESP8266上要什么编码格式啊。这个才是重点。

**Comment by chengxinping** [comment]
06-04 16:23:20.740 2362-2460/com.delicloud.app.airkissdemo W/System.err: java.lang.IllegalArgumentException: illegal length or offset
06-04 16:23:20.741 2362-2460/com.delicloud.app.airkissdemo W/System.err:     at java.net.DatagramPacket.setData(DatagramPacket.java:263)
        at java.net.DatagramPacket.<init>(DatagramPacket.java:115)
        at java.net.DatagramPacket.<init>(DatagramPacket.java:156)


只要是使用中文SSID 就抱这个错误
